### ISSUE TITLE
System topics load randomly

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript-editor#19] opened 2015-05-19 15:04 UTC
From #14:

> > Created a system topic, but the bot jumped into it from 'random' topic. I thought that system topics were called only specifically. 
> 
> This is a bug and you are right. System topics should be unreachable.

**Comment by silentrob** [comment] 2015-05-19 17:43
Interesting. I was not able to reproduce this.
1. Created a system topic with one gambit. 
2. Tested the gambit from the gambit test interface (Matched)
3. Tested the gambit from the topic test interface. (Matched)
4. Tested from the chat interface. (No Match)
5. Test random gambit - in random topic. (Matched)
6. Added ^resond(...) function to gambit in random topic and it shows up literal string escaped (BUG)

**Comment by silentrob** [comment] 2015-05-19 17:45
Can you verify or provide some step to repo this. Or close it if it is indeed invalid. Thanks!

**Closed as completed** 2015-05-31 18:19 UTC
Labels: invalid
